apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
  - name: welcome-http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP