apiVersion: apps/v1
kind: Deployment
metadata:  
  name: my-first-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:  
      labels:
        app: web-app
    spec:
      containers:
      - image: fpommerening/container-training:webapp-v1
        name: app