apiVersion: apps/v1
kind: Deployment
metadata:  
  name: my-first-deployment
  annotations:
    kubernetes.io/change-cause: "image updated to v3"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:  
      labels:
        app: web-app
    spec:
      containers:
      - image: fpommerening/container-training:webapp-v3
        name: app